### ISSUE TITLE
Add Windows Continuous Integration Supports

### ISSUE THREAD

**Issue by willyd** [willyd/caffe#1]
Appveyor seems interesting.

**Comment by bhack** [comment]
I hope that window will arrive soon see https://github.com/travis-ci/travis-ci/issues/216

**Comment by willyd** [comment]
@bhack Looking at this thread and others it is very hard to conclude when this will be.

**Comment by willyd** [comment]
CUDA is still missing in Appveyor. See https://github.com/appveyor/ci/issues/342
