### ISSUE TITLE
classification with GPU

### ISSUE THREAD

**Issue by naranjuelo** [willyd/caffe#14]
I found the classification example (classification.cpp) interesting, but I'm trying implement it with GPU instead of CPU with no success...

Anyone that has already done it could help me?? thank you!!

**Comment by willyd** [comment]
@naranjuelo Never used that particular example but it looks like that the GPU mode will be enabled by default if you compiled with GPU. See https://github.com/willyd/caffe/blob/master/examples/cpp_classification/classification.cpp#L55.

If you use the caffe.exe to train your own model the GPU mode can be set via the solver proto like described in the official docs.

Please ask your usage questions on the official caffe mailing list (google groups) as it will reach a larger audience.
