### ISSUE TITLE
Problems compiling windows-cmake branch

### ISSUE THREAD

**Issue by lunzueta** [willyd/caffe#16]
Hi @willyd. I'm trying to compile the new windows-cmake branch of this repo, but I get this linking error when compiling the "caffe.bin" project (after compiling correctly its dependency "caffe"):

```
3>caffe.obj : error LNK2019: unresolved external symbol "void __cdecl caffe::caffe_gpu_dot<float>(int,float const *,float const *,float *)" (??$caffe_gpu_dot@M@caffe@@YAXHPEBM0PEAM@Z) referenced in function "public: float __cdecl caffe::Layer<float>::Forward(class std::vector<class caffe::Blob<float> *,class std::allocator<class caffe::Blob<float> *> > const &,class std::vector<class caffe::Blob<float> *,class std::allocator<class caffe::Blob<float> *> > const &)" (?Forward@?$Layer@M@caffe@@QEAAMAEBV?$vector@PEAV?$Blob@M@caffe@@V?$allocator@PEAV?$Blob@M@caffe@@@std@@@std@@0@Z)
```

Could this be because I'm using CUDA 7.5 instead of 7.0, as I think you are using, because of the comments written here: https://github.com/willyd/caffe-builder? Can you compile it correctly?

**Comment by willyd** [comment]
I should update the readme as I am also using 7.5. I will get back to you on this. Yes everything works fine on my side.

**Comment by lunzueta** [comment]
Sorry, I didn't give too much detail before about what I tried, exactly. I tried to compile this branch by using CMake GUI to configure and generate the solution for Visual Studio 2013, and then compile it with Visual Studio 2013. That way I had problems to compile "caffe.bin", as said before. Did you try to do this?

I've also tried to compile this using ninja as you explained here (https://github.com/BVLC/caffe/pull/3990) and I can generate all the files correctly after a second attempt. It's a bit strange I have to run ninja twice to get this done. After the second attempt then if I run ninja again I get a message saying "ninja: no work to do", so I assume everything is done. I attach the outputs I get in the console after each attempt. Please, let me know if this behavior is different from what you see in your side.

[output2.txt](https://github.com/willyd/caffe/files/222761/output2.txt)
[output1.txt](https://github.com/willyd/caffe/files/222762/output1.txt)

(Off topic: I'm really impressed with the speed in which Ninja compiles CUDA files compared to Visual Studio :-O)

**Comment by willyd** [comment]
@lunzueta I did not try the Visual Studio Generator. I may when I have time. So the unresolved symbol could be due to a difference between ninja and VS. Can you find a `caffe.def` file somewhere in the build directory? Are there any differences between the ninja and VS generated files?

As for the fact that you need to run ninja twice, this seems to be due to post build events that try to copy the same files to the same locations. I will try to push a fix for this soon and let you know.

**Comment by willyd** [comment]
@lunzueta I noticed that some symbols are not correctly exported making caffe.exe and other tools unsuable. Stay tuned for more info.

**Comment by willyd** [comment]
@lunzueta I fixed the missing layers and solvers on windows-cmake branch. windows-cmake-wip also has more changes that you could be interested in.

**Comment by lunzueta** [comment]
@willyd It worked now! Thank you!
This time everything went smooth with Ninja for the compilation of the windows-cmake branch. Then, I was able to train mnist correctly with the caffe.exe command. I've tested this in Release and also in Debug (without the python layer in this case as I didn't have the python27_d.lib file).

So, I guess that the windows-cmake-wip branch is a "work-in-progress" branch, and windows-cmake is a more stable branch, isn't it?

**Comment by willyd** [comment]
> @willyd It worked now! Thank you!

Great.

> (without the python layer in this case as I didn't have the python27_d.lib file).

You are assuming this does not work or you had problems with it? It should work ok without the debug python lib (It works on my side, the only thing you need to do it to rename the .pyd from caffe-d.pyd to caffe.pyd). See http://www.boost.org/doc/libs/1_60_0/libs/python/doc/html/building/python_debugging_builds.html and https://github.com/willyd/caffe/blob/windows-cmake/python/caffe/_caffe.cpp#L1

> So, I guess that the windows-cmake-wip branch is a "work-in-progress" branch, and windows-cmake is a more stable branch, isn't it?

They are both work in progress but I use the WIP to validate that some commits pass the CI tests.  So stick to the none WIP branch.

**Comment by lunzueta** [comment]
I tried to compile it again in Debug with the python layer activated and this time it worked. I didn't have to rename that file, maybe because this time it was using the caffe.pyd file I already had compiled in Release (I've compile both in the same build folder), as the output says the following:

`[191/191] Linking CXX shared module lib\_caffe.pyd
   Creating library lib\_caffe.lib and object lib\_caffe.exp
-- Resolving dependencies for C:/caffe/build/lib/_caffe.pyd...
-- Copying resolved dependencies for C:/caffe/build/lib/_caffe.pyd to C:/caffe/python/caffe...`
