### ISSUE TITLE
Implement filesystem related functions using boost filesystem

### ISSUE THREAD

**Issue by willyd** [willyd/caffe#2]
Use boost filesystem instead of Unix specific implementations of:

MakeTempFile
MakeTmpDir
mkdir

**Comment by bhack** [comment]
This will potentially conflict with https://github.com/BVLC/caffe/pull/2537

**Comment by willyd** [comment]
Should we rely on C++14 `<filesystem>` then?

**Comment by bhack** [comment]
Yes but you need to investigate what are the minimal g++ clang and msvc version  that support that and if this minimal versions are acceptable by core Caffe developers.

**Comment by eelstork** [comment]
I'm working on this.

**Comment by willyd** [comment]
@eelstork Great looking forward to try it!

**Comment by eelstork** [comment]
@willyd does #3300 answer this?

**Comment by willyd** [comment]
Yes I will close the issue when I merge these changes.

**Comment by eelstork** [comment]
@willyd I filed #3324 which looks related to this. Advising caution.

**Comment by willyd** [comment]
Closing fixed by: https://github.com/BVLC/caffe/pull/3300 and https://github.com/BVLC/caffe/pull/3446
