### ISSUE TITLE
Weird inclusion of some 3rd parties

### ISSUE THREAD

**Issue by lunzueta** [willyd/caffe#22]
Hi @willyd. I'm trying to include Caffe as a external library to my own library, but instead of following your command-based cmake instructions, I'm trying to do this based on cmake-gui, which doesn't work in the same way, as we already discussed in https://github.com/willyd/caffe/issues/19.

So, in my project I include Caffe and the third parties like this:

```
FIND_PACKAGE( Boost COMPONENTS atomic chrono date_time filesystem python system thread )
FIND_PACKAGE( OpenCV )
FOREACH( _pkg ZLIB gflags glog protobuf HDF5 OpenBLAS LevelDB LMDB Snappy )
    FIND_PACKAGE( ${_pkg} )
ENDFOREACH()
FIND_PACKAGE( Caffe REQUIRED )
```

Then, what I see in Visual Studio, once I generate the project is that there are some libraries which are included in a weird way:
- OpenBLAS.lib -> this file doesn't exist
- libprotobuf.lib -> the path to this file isn't included, so the linker can't find the file

Then, I tried to do the following:

```
FIND_PACKAGE( Boost COMPONENTS atomic chrono date_time filesystem python system thread )
FIND_PACKAGE( OpenCV )
FOREACH( _pkg ZLIB gflags glog protobuf HDF5 OpenBLAS LevelDB LMDB Snappy )
    FIND_PACKAGE( ${_pkg} )
ENDFOREACH()
FIND_PACKAGE( Caffe REQUIRED )
SET( Caffe_INCLUDE_DIRS
    ${Caffe_INCLUDE_DIRS}
    ${Protobuf_INCLUDE_DIR}
    ${OpenBLAS_INCLUDE_DIRS}
)
SET( Caffe_LIBRARIES
    ${Caffe_LIBRARIES}
    optimized ${Protobuf_LIBRARY_RELEASE}
    debug ${Protobuf_LIBRARY_DEBUG}
    ${OpenBLAS_LIBRARIES}
)
```

And this time, in Visual Studio, the linker showed me the following additional libraries:
- \home\traits\project\pack_openblas\OpenBLAS-v0.2.14-Win64-int32\bin\libopenblas.dll -> the path isn't valid for Windows systems
- C:\Anaconda2\envs\caffe\Library\lib\libprotobuf.lib -> this is correct

What should be changed in the Conda packages to make this work?

**Comment by willyd** [comment]
Hi @lunzueta, this looks like your library is not finding the right protobuf and openblas libraries. The trick is to correctly set the CMAKE_PREFIX_PATH and CMAKE_MODULE_PATH variables. What I noticed is that when one uses the command line setting those works well. However, when using the cmake-gui you can set them and they will work as expected but you will need to set them before every configure. One workaround is to set them in your own CMakeLists.txt like so:

```
set(CMAKE_MODULE_PATH <module_path>)
set(CMAKE_PREFIX_PATH <prefix_path>)
```

you can see the values you should use for module and prefix path by doing:

```
> set_cmake_vars.bat
> echo %CMAKE_MODULE_PATH%
> echo %CMAKE_PREFIX_PATH%
```

Let me know if this solves the problem. 

In the end, I find this module and prefix path thing a little too automagical so I am currently updating my windows-cmake branch in order to remove the conda packages and remove the need for the module and prefix path. I will let you know when it is ready so you can test the update.

Thanks

**Comment by willyd** [comment]
@lunzueta, @PaulDufort. Can you please try the latest windows-cmake branch of this repository and let me know if it works for you. This will be the basis of the new BVLC/caffe/windows branch. 

@lunzueta It should work with the Ninja or the Visual Studio generator so use whatever you are more comfortable with. No need for CMAKE_MODULE_PATH or CMAKE_PREFIX_PATH to be set either, so it should work from the CMake-Gui as well. All you need is to make sure your cache is initialized with the variables contained in the caffe-builder-config.cmake. In my opinion the easiest way to do this is still by using the `-C` command line switch of the cmake executable.

You may also wish to build the dependencies yourself using caffe-builder.

Please let me know:
- How smooth is the build process?
- Do tests pass (except for GPUTimer)?

Thanks

**Comment by lunzueta** [comment]
Hi @willyd. Thanks for the update. I used cmake-gui to generate the solution for Visual Studio and I only had to make a couple of manual changes to make it work. Then, VS compiled directly without further changes. I think this way of providing the 3rd parties is much clearer than the previous approach.

The changes I did in cmake-gui were:
- Set manually the path to libopenblas.dll.a because it couldn't find it automatically.
- Disable USE_CUDNN (well, I guess this will be fixed after updating Caffe with BVLC's master branch)
- Enable protobuf_MODULE_COMPATIBLE (don't really know why this needs to be done, so it might be a bit confusing for users)
- Fix the path found for ZLIB_LIBRARY_RELEASE, as it's taking the one I had installed in Anaconda (the debug one is correctly found)
- Set manually the path to HDF5_ROOT_DIR as it can't be found automatically and if it isn't provided it gives an error

Some other observations about this:
- In VS I can see that there's a repetition in the zlib libraries linked to the project: ..\..\libraries\CMake\..\lib\zlib.lib and ..\..\libraries\lib\zlib.lib in Release, and ..\..\libraries\CMake\..\lib\zlibd.lib and ..\..\libraries\lib\zlibd.lib in Debug. I think this should be easy to fix.

I'll do more detailed tests with the compiled Caffe and I'll let you know if I find something else.

(off topic: thanks for recommending VS Code in your instructions, I didn't know it and it looks a great tool)

**Comment by willyd** [comment]
@lunzueta Thanks for testing this. Did you use the caffe-builder-config.cmake to initialize the cache with the command line before firing up cmake-gui? I guess you did not since you wouldn't have had to set all those  variables manually.

> Enable protobuf_MODULE_COMPATIBLE (don't really know why this needs to be done, so it might be a bit confusing for users)

I will make this one part of the caffe CMakeLists.txt so it's less confusing.

> In VS I can see that there's a repetition in the zlib libraries linked to the project: ....\libraries\CMake..\lib\zlib.lib and ....\libraries\lib\zlib.lib in Release, and ....\libraries\CMake..\lib\zlibd.lib and ....\libraries\lib\zlibd.lib in Debug. I think this should be easy to fix.

is there really a missing backslash? Should I read \libraries\CMake**\**..\lib\zlib.lib instead of \libraries\CMake..\lib\zlib.lib.

**Comment by lunzueta** [comment]
> Did you use the caffe-builder-config.cmake to initialize the cache with the command line before firing up cmake-gui? I guess you did not since you wouldn't have had to set all those  variables manually.

No I didn't, but it was on purpose. I just wanted to test this in the way I'd normally use cmake-gui (without opening the console at all), like with other projects (e.g. OpenCV).

> I will make this one part of the caffe CMakeLists.txt so it's less confusing.

Thanks.

> is there really a missing backslash? Should I read \libraries\CMake**\**..\lib\zlib.lib instead of \libraries\CMake..\lib\zlib.lib.

Sorry, it was my fault when writing the comment. I didn't realize that I needed to add some extra backslashes so that the final text looked good (I've corrected the typos).

**Comment by lunzueta** [comment]
@willyd, regarding the automatic search of `libopenblas.dll.a` you might use something like this:

```
SET( CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".dll" ".a" )
FIND_LIBRARY( OPENBLAS_LIBRARY NAMES libopenblas.dll.a PATHS ${CMAKE_SOURCE_DIR}/libraries/lib )
```

**Comment by lunzueta** [comment]
@willyd, I just did some more detailed tests with this Caffe version linked externally to another library (load/save datasets in lmdb, leveldb and hdf5 formats, train/test nets and deploy trained models, using CPU/GPU), and everything went fine :-)

I configured the Caffe dependence in my project, in CMake, like this:

```
FIND_PACKAGE( Boost COMPONENTS atomic chrono date_time filesystem python system thread )
FOREACH( _pkg ZLIB gflags glog protobuf HDF5 OpenBLAS LevelDB LMDB Snappy OpenCV )
    FIND_PACKAGE( ${_pkg} )
ENDFOREACH()
FIND_PACKAGE( Caffe REQUIRED )

SET( CVMLAUX_INCLUDE_DIRS
    ${Boost_INCLUDE_DIR}
    ${Caffe_INCLUDE_DIRS}
    ${OpenCV_INCLUDE_DIRS}
    )
SET( CVMLAUX_LIBRARIES
    ${Caffe_LIBRARIES}
    ${OpenCV_LIBRARIES}
    )

ADD_DEFINITIONS( -DBOOST_ALL_NO_LIB ${Caffe_DEFINITIONS} )
```

As you can see, it was necessary to include "BOOST_ALL_NO_LIB" in the preprocessor definitions, otherwise I had linking problems with leveldb in my library, because of Boost. I guess this should be explained in the instructions too, because it's not straightforward to know how to fix that problem.

**Comment by willyd** [comment]
@lunzueta Thanks for pointing this out. I will add the definitions to both leveldb and caffe exported targets.

Have you tried to remove the `find_package` calls? If I implemented them correctly in https://github.com/willyd/caffe/blob/windows-cmake/cmake/Templates/CaffeConfig.cmake.in it should not be necessary anymore.

**Comment by lunzueta** [comment]
Hi @willyd. I tested this again and I could remove all find_packages, except those for Boost and OpenCV. Should it be this way?

**Comment by willyd** [comment]
@lunzueta 

No looking at the code. The CMake code is plain wrong for OpenCV.

For boost I guess I supposed that we only needed the libraries, but since caffe uses boost::shared_ptr we need the headers.

I will add them thanks. For reporting.

**Comment by willyd** [comment]
@lunzueta I think I fixed OpenCV. 

Turns out you should not need a find_package(Boost) since the library paths are hard-coded in the CaffeConfig.cmake and the boost include dir should be included in the Caffe_INCLUDE_DIRS variable.

Please note that I rebased my windows-cmake branch to have single commit on top of the current windows branch to ease the merge. A simple `git pull` will most probably fail, instead you will need to:

```
git checkout windows-cmake
git fetch
git reset --hard origin/windows-cmake
```

**Comment by lunzueta** [comment]
@willyd OK, I updated my local copy of your repo that way (just in case I also downloaded again the 3rd parties), I compiled Caffe, linked it externally to my project using only Caffe's CMake variables (Caffe_INCLUDE_DIRS, Caffe_LIBRARIES, Caffe_DEFINITIONS), but when compiling my project I had the failure of not having found 'boost/shared_ptr.hpp', so I guess there's still something to be fixed in one CMake file so that Boost header files can be found.

**Comment by PaulDufort** [comment]
@willyd OK, I followed the instructions in caffe-builder and saved the output to the attached log file. There didn't seem to be any catastrophic failures, but I'm not familiar enough with these tools to have much more to say than that. Please let me know what I can do next.
[log.txt](https://github.com/willyd/caffe/files/526038/log.txt)

**Comment by willyd** [comment]
@PaulDufort It seems that everything went through sucessfully you should now have a `libraries` folder in `F:/Caffe/caffe-builder/build_v120_x64`.

What you want to do next is to configure caffe and build it using cmake. Clone my latest `windows-cmake` branch and follow the readme there where `%caffe_dependencies%` should be `F:/Caffe/caffe-builder/build_v120_x64/libraries`.

**Comment by PaulDufort** [comment]
There are five branches with the "windows-cmake" prefix, and I can't
seem to tell which is the latest - which one did you mean?

On Thu, Oct 13, 2016, at 12:04 PM, Guillaume Dumont wrote:

> @PaulDufort[1] It seems that everything went through sucessfully you
> should now have a libraries folder in F:/Caffe/caffe-
> builder/build_v120_x64.
> What you want to do next is to configure caffe and build it using
> cmake. Clone my latest windows-cmake branch and follow the readme
> there where %caffe_dependencies% should be F:/Caffe/caffe-
> builder/build_v120_x64/libraries.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].

Links:
1. https://github.com/PaulDufort
2. https://github.com/willyd/caffe/issues/22#issuecomment-253558696

**Comment by willyd** [comment]
@PaulDufort sorry for the misunderstanding, yes my repo is a bit of a mess right now.

The active branches are:
- windows-cmake (== BVLC/windows + cmake support)
- windows-cmake-merge (==BVLC/windows + cmake support + latest BVLC/master changes)

Use windows-cmake for now.

You can ignore windows-cmake2, and the wip branches.

**Comment by PaulDufort** [comment]
No worries - will try it tonight!

On Thu, Oct 13, 2016, at 02:07 PM, Guillaume Dumont wrote:

> @PaulDufort[1] sorry for the misunderstanding, yes my repo is a bit of
> a mess right now.
> The active branches are:
> - windows-cmake (== BVLC/windows + cmake support)
> - windows-cmake-merge (==BVLC/windows + cmake support + latest
>   BVLC/master changes)
>   Use windows-cmake for now.
>   You can ignore windows-cmake2, and the wip branches.
>   — You are receiving this because you were mentioned. Reply to this
>   email directly, view it on GitHub[2], or mute the thread[3].

Links:
1. https://github.com/PaulDufort
2. https://github.com/willyd/caffe/issues/22#issuecomment-253592177

**Comment by PaulDufort** [comment]
Hey @willyd, it all seems to have worked! Ran the tests and 2001 out of 2005 tests passed - the only ones that failed are as follows:

[----------] Global test environment tear-down
[==========] 2005 tests from 269 test cases ran. (1060607 ms total)
[  PASSED  ] 2001 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] BenchmarkTest/2.TestTimerMilliSeconds, where TypeParam = struct caffe::GPUDevice<float>
[  FAILED  ] BenchmarkTest/2.TestTimerSeconds, where TypeParam = struct caffe::GPUDevice<float>
[  FAILED  ] BenchmarkTest/3.TestTimerMilliSeconds, where TypeParam = struct caffe::GPUDevice<double>
[  FAILED  ] BenchmarkTest/3.TestTimerSeconds, where TypeParam = struct caffe::GPUDevice<double>

 4 FAILED TESTS

These all seem to have to do with GPU timing, which was listed as a known issue, so I'm guessing that all the tests that were supposed to pass, did pass.

**Comment by willyd** [comment]
@PaulDufort Yey! I'll let you know when this branch is merged in BVLC-windows and master is merged in too. Thanks for your help! Have fun.

**Comment by PaulDufort** [comment]
@willyd Thanks very much for all your work on this! I can't believe how easy you made it. I took your advice and used Ninja, so my laptop roared up to 100% usage of its four cores but it was all over quickly.

One question: I am used to managing projects and their source files through Visual Studio, or with make files in UNIX in the distant past. How do you add new layer source code files to the project under this CMake framework? How do you edit source files and then re-generate the executables?

**Comment by lunzueta** [comment]
@willyd I've done further tests with your last updates. This time, for linking Caffe in my project, I had to include this in my project's CMake, so that the VS solution could be generated correctly using cmake-gui, without having to use the console:

```
FIND_PACKAGE( Boost COMPONENTS atomic chrono date_time filesystem python system thread )
FIND_PACKAGE( Caffe REQUIRED )
FIND_PACKAGE( OpenCV REQUIRED )
SET( CVMLAUX_INCLUDE_DIRS
    ${Boost_INCLUDE_DIR}
    ${Caffe_INCLUDE_DIRS}
)
SET( CVMLAUX_LIBRARIES
    ${Caffe_LIBRARIES}
    ${OpenCV_LIBRARIES}
)
ADD_DEFINITIONS( ${Caffe_DEFINITIONS} )
```

So, as you can see, no need to add "BOOST_ALL_NO_LIB" and most of the 3rd parties (except Boost and OpenCV), and no need to change anything in VS, afterwards. Well, I'm happy enough with this. It's much cleaner than it was before. Thanks for your efforts on this :-)

**Comment by willyd** [comment]
@PaulDufort Thanks for your feedback. Happy that it worked for you. If you want to be able to do things on your laptop you can call `ninja -j2` to set the number of concurrent jobs like with Make. 

> One question: I am used to managing projects and their source files through Visual Studio, or with make files in UNIX in the distant past. How do you add new layer source code files to the project under this CMake framework? How do you edit source files and then re-generate the executables?

CMake works with the `add_executable` and `add_library` commands where you list your source files. If your CMakeLists.txt lists all the sources one by one than CMake will pickup that you changed the CMakeLists.txt file and will renegerate the Makefiles or VS projects. If you do like caffe does and use `file(GLOB ...)` you will have to issue the `cmake` command again to regenerate the build system files because CMake cannot detect that something changed. Using ninja you can always call `ninja build.ninja` to rerun CMake and the ZERO_CHECK project in VS would do the same. But those two commands won't pickup the new files when using GLOB.

**Comment by willyd** [comment]
@lunzueta Good. I still don't understand why you have to find Boost and OpenCV manually. Are you using these in your own project? That may explain why, anyhow I will try to see if this can be improved but I agree this is a minor issue. I have bigger fish to fry right now. ;)

**Comment by PaulDufort** [comment]
@willyd If I were to use VS2013 as the build generator instead of Ninja, would a VS solution then be created that I could open and use to edit/add source files and rebuild like any other VS project? Or is it more complicated than that?

Also FYI, I tried the build again tonight with cuDNN 5.0 and 5.1 (yesterday's successful build was with cuDNN 4.0) and it failed, due to some apparent API changes - it appears to be a known problem. I'm guessing this will probably be resolved in future updates to Caffe.

Thanks again,
Paul

**Comment by lunzueta** [comment]
Hi @PaulDufort. Yes, you can generate a VS solution with CMake and then work with the generated VS solution in the normal way. If you are using the console, as shown in @willyd's instructions, then you'd replace `set CMAKE_GENERATOR=Ninja` by `set CMAKE_GENERATOR="Visual Studio 12 2013"` or other possibilities that you can check with the command `cmake --help`. Alternatively, you can use cmake-gui, which comes with cmake too, which allows you to set these parameters in a more graphical way. CMake is a great tool, indeed. You should check how it works more in detail: https://cmake.org/cmake-tutorial/

@willyd, yes, that's right, some header files from Boost and OpenCV are included explicitly in my project, apart from those of Caffe, so that's probably the reason of it. Anyway, their inclusion is also derived from the practical use of Caffe functionalities, so they aren't so optional (at least at first glance, taking into account the provided examples of the use of Caffe functionalities). For example, the inclusion of `boost/scoped_ptr.hpp` is required because of functions like this (as shown in convert_cifar_data.cpp and convert_mnist_data.cpp examples):

```
boost::scoped_ptr<caffe::db::DB> db(caffe::db::GetDB("leveldb"));
```

I guess that in some cases this explicit inclusion of Boost could be avoided by using equivalent functions from the C++ standard library, but this isn't something that can be done always for sure, especially taking into account that there might be some differences in the "Standard" if we consider different compilers.

So, I'd say that the issue reported in this thread is currently solved, so I'll close it. You are right, there are more important issues at this moment for the Windows version of Caffe (for example, to put it at the same level as the master branch of BVLC's repo). Let us know if you'd need further help.

**Comment by willyd** [comment]
> @willyd If I were to use VS2013 as the build generator instead of Ninja, would a VS solution then be created 

Yes.

> that I could open and use to edit/add source files and rebuild like any other VS project? Or is it more complicated than that?

No you can't add files or build settings through the VS UI these changes all have to be made to the CMake files and the VS projects have then to be regenerated. Actually, to be exact you can add files but all changes you make to the solution will be lost when CMake regenerates the project files.

> Also FYI, I tried the build again tonight with cuDNN 5.0 and 5.1 (yesterday's successful build was with cuDNN 4.0) and it failed, due to some apparent API changes - it appears to be a known problem. I'm guessing this will probably be resolved in future updates to Caffe.

I believe this is going to work when the latest master is merge in. This should happen sooner than later.
