### ISSUE TITLE
Use a cross-platform sleep function to replace usleep

### ISSUE THREAD

**Issue by willyd** [willyd/caffe#3]
``` C++
#include <boost/thread/thread.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>

boost::this_thread::sleep(boost::posix_time::millisec(milliseconds));
```

or C++11

``` C++
#include <chrono>
#include <thread>

std::this_thread::sleep_for(std::chrono::milliseconds(ms));
```

**Comment by willyd** [comment]
The above implementation might not be sufficient to make the GPU Timer test pass.

**Comment by lunzueta** [comment]
In this thread some suggestions are made:
http://stackoverflow.com/questions/10918206/cross-platform-sleep-function-for-c

From these the one that I like most, because of its simplicity, is this one:

```
#ifdef _WINDOWS
#include <windows.h>
#else
#include <unistd.h>
#define Sleep(x) usleep((x)*1000)
#endif
```

Then use like this:

```
Sleep(how_many_milliseconds);
```

Maybe something similar to this could be used. Would this help?

**Comment by bhack** [comment]
http://en.cppreference.com/w/cpp/thread/sleep_for

**Comment by willyd** [comment]
see issue #2

**Comment by willyd** [comment]
Closing fixed by: https://github.com/BVLC/caffe/pull/3300/files
