### ISSUE TITLE
Implement cross-platform snprintf

### ISSUE THREAD

**Issue by willyd** [willyd/caffe#4]
Windows does not have snprintf:

See this PR for possible implementation
https://github.com/BVLC/caffe/pull/2084/

Otherwise maybe we can use #define s like in gtest_all.cc

**Comment by lunzueta** [comment]
According to this discussion (http://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010) the possible solutions to this in Windows depend on the Visual Studio version used. I guess that it is necessary to specify which would be the minimal VS version that should be used for Caffe.

Besides, I guess that MinGW should also be taken into account and not only Visual Studio, but I'm not familiar to it. Here some comments about this:
http://sourceforge.net/p/mingw-w64/mailman/message/31241434/

**Comment by bhack** [comment]
http://stackoverflow.com/questions/5847480/what-is-the-c-idiom-to-replace-snprintf3

**Comment by eelstork** [comment]
Fixed on master (see #3361)

**Comment by willyd** [comment]
Closing fixed by: https://github.com/BVLC/caffe/pull/3361
